# Generated by Django 3.2.12 on 2023-05-23 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('id_ensg', models.AutoField(primary_key=True, serialize=False)),
                ('nom_eng', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('telph', models.IntegerField()),
                ('Diplome', models.CharField(max_length=50)),
                ('Statut', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='img/')),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('date_naissance', models.DateField()),
                ('lieu_naissance', models.CharField(max_length=50)),
                ('pays_naissance', models.CharField(max_length=50)),
                ('departement', models.CharField(max_length=50)),
                ('voie_acces', models.CharField(max_length=10)),
                ('matricule', models.CharField(max_length=50)),
                ('nationalite', models.CharField(max_length=50)),
                ('nni', models.CharField(max_length=50)),
                ('statut', models.CharField(max_length=50)),
                ('annee_inscription', models.IntegerField()),
            ],
        ),
    ]
